-- BL-072: curated landing catalog membership lives in the database instead of a Java list.
-- status controls landing/search membership only; inactive never touches books or generated art.
-- Seeded from the former CuratedCatalogService list (all active).
CREATE TABLE curated_books (
    id VARCHAR(255) PRIMARY KEY,
    source VARCHAR(32) NOT NULL,
    source_id VARCHAR(64) NOT NULL,
    title VARCHAR(512) NOT NULL,
    author VARCHAR(512) NOT NULL,
    popularity INTEGER NOT NULL,
    subjects_json TEXT NOT NULL,
    bookshelves_json TEXT NOT NULL,
    aliases_json TEXT NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_curated_books_source UNIQUE (source, source_id),
    CONSTRAINT ck_curated_books_status CHECK (status IN ('active', 'inactive'))
);

INSERT INTO curated_books
    (id, source, source_id, title, author, popularity, subjects_json, bookshelves_json, aliases_json, status, created_at, updated_at)
VALUES
('gutenberg:1342', 'gutenberg', '1342', 'Pride and Prejudice', 'Jane Austen', 100000, '["Courtship fiction"]', '["Romance"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:2701', 'gutenberg', '2701', 'Moby Dick', 'Herman Melville', 99000, '["Whaling -- Fiction"]', '["Adventure"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:84', 'gutenberg', '84', 'Frankenstein', 'Mary Shelley', 98000, '["Science fiction"]', '["Horror"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:345', 'gutenberg', '345', 'Dracula', 'Bram Stoker', 97000, '["Vampires -- Fiction"]', '["Gothic"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:11', 'gutenberg', '11', 'Alice''s Adventures in Wonderland', 'Lewis Carroll', 96000, '["Fantasy fiction"]', '["Children"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:1260', 'gutenberg', '1260', 'Jane Eyre', 'Charlotte Bronte', 95000, '["Governesses -- Fiction"]', '["Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:768', 'gutenberg', '768', 'Wuthering Heights', 'Emily Bronte', 94000, '["Love stories"]', '["Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:174', 'gutenberg', '174', 'The Picture of Dorian Gray', 'Oscar Wilde', 93000, '["Psychological fiction"]', '["Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:98', 'gutenberg', '98', 'A Tale of Two Cities', 'Charles Dickens', 92000, '["Historical fiction"]', '["Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:1184', 'gutenberg', '1184', 'The Count of Monte Cristo', 'Alexandre Dumas', 91000, '["Adventure stories"]', '["Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:2554', 'gutenberg', '2554', 'Crime and Punishment', 'Fyodor Dostoyevsky', 90000, '["Psychological fiction"]', '["Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:1399', 'gutenberg', '1399', 'Anna Karenina', 'Leo Tolstoy', 89000, '["Domestic fiction"]', '["Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:1661', 'gutenberg', '1661', 'The Adventures of Sherlock Holmes', 'Arthur Conan Doyle', 88000, '["Detective and mystery stories"]', '["Detective Fiction"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:1727', 'gutenberg', '1727', 'The Odyssey', 'Homer', 87000, '["Epic poetry"]', '["Poetry"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:996', 'gutenberg', '996', 'Don Quixote', 'Miguel de Cervantes', 86000, '["Satire"]', '["Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:135', 'gutenberg', '135', 'Les Miserables', 'Victor Hugo', 85000, '["Historical fiction"]', '["Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:2600', 'gutenberg', '2600', 'War and Peace', 'Leo Tolstoy', 84000, '["Historical fiction"]', '["Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:28054', 'gutenberg', '28054', 'The Brothers Karamazov', 'Fyodor Dostoyevsky', 83000, '["Brothers -- Fiction"]', '["Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:120', 'gutenberg', '120', 'Treasure Island', 'Robert Louis Stevenson', 82000, '["Treasure troves -- Fiction"]', '["Adventure"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:25344', 'gutenberg', '25344', 'The Scarlet Letter', 'Nathaniel Hawthorne', 81000, '["Adultery -- Fiction"]', '["Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:1400', 'gutenberg', '1400', 'Great Expectations', 'Charles Dickens', 80000, '["Orphans -- Fiction"]', '["Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:76', 'gutenberg', '76', 'Adventures of Huckleberry Finn', 'Mark Twain', 79000, '["Boys -- Fiction"]', '["Adventure"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:46', 'gutenberg', '46', 'A Christmas Carol', 'Charles Dickens', 78000, '["Christmas stories"]', '["Holiday"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:43', 'gutenberg', '43', 'The Strange Case of Dr. Jekyll and Mr. Hyde', 'Robert Louis Stevenson', 77000, '["Personality disorders -- Fiction"]', '["Horror"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:35', 'gutenberg', '35', 'The Time Machine', 'H. G. Wells', 76000, '["Time travel -- Fiction"]', '["Science Fiction"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:36', 'gutenberg', '36', 'The War of the Worlds', 'H. G. Wells', 75000, '["Martians -- Fiction"]', '["Science Fiction"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:5230', 'gutenberg', '5230', 'The Invisible Man', 'H. G. Wells', 74000, '["Science fiction"]', '["Science Fiction"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:2488', 'gutenberg', '2488', 'Twenty Thousand Leagues Under the Seas', 'Jules Verne', 73000, '["Sea stories"]', '["Adventure"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:103', 'gutenberg', '103', 'Around the World in Eighty Days', 'Jules Verne', 72000, '["Voyages around the world -- Fiction"]', '["Adventure"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:18857', 'gutenberg', '18857', 'Journey to the Centre of the Earth', 'Jules Verne', 71000, '["Science fiction"]', '["Adventure"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:37106', 'gutenberg', '37106', 'Little Women', 'Louisa May Alcott', 70000, '["Sisters -- Fiction"]', '["Children"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:17396', 'gutenberg', '17396', 'The Secret Garden', 'Frances Hodgson Burnett', 69000, '["Gardens -- Fiction"]', '["Children"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:16', 'gutenberg', '16', 'Peter Pan', 'J. M. Barrie', 68000, '["Fantasy fiction"]', '["Children"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:55', 'gutenberg', '55', 'The Wonderful Wizard of Oz', 'L. Frank Baum', 67000, '["Fantasy fiction"]', '["Children"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:52521', 'gutenberg', '52521', 'Grimm''s Fairy Tales', 'Jacob Grimm', 66000, '["Fairy tales"]', '["Children"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:215', 'gutenberg', '215', 'The Call of the Wild', 'Jack London', 65000, '["Dogs -- Fiction"]', '["Adventure"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:219', 'gutenberg', '219', 'Heart of Darkness', 'Joseph Conrad', 64000, '["Psychological fiction"]', '["Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:940', 'gutenberg', '940', 'The Last of the Mohicans', 'James Fenimore Cooper', 63000, '["Historical fiction"]', '["Adventure"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:1257', 'gutenberg', '1257', 'The Three Musketeers', 'Alexandre Dumas', 62000, '["Adventure stories"]', '["Adventure"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:161', 'gutenberg', '161', 'Sense and Sensibility', 'Jane Austen', 61000, '["Domestic fiction"]', '["Romance"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:105', 'gutenberg', '105', 'Persuasion', 'Jane Austen', 60000, '["Domestic fiction"]', '["Romance"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:141', 'gutenberg', '141', 'Mansfield Park', 'Jane Austen', 59000, '["Domestic fiction"]', '["Romance"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:121', 'gutenberg', '121', 'Northanger Abbey', 'Jane Austen', 58000, '["Young women -- Fiction"]', '["Romance"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:145', 'gutenberg', '145', 'Middlemarch', 'George Eliot', 57000, '["Domestic fiction"]', '["Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:766', 'gutenberg', '766', 'David Copperfield', 'Charles Dickens', 56000, '["Bildungsromans"]', '["Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:730', 'gutenberg', '730', 'Oliver Twist', 'Charles Dickens', 55000, '["Orphans -- Fiction"]', '["Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:1837', 'gutenberg', '1837', 'The Prince and the Pauper', 'Mark Twain', 54000, '["Princes -- Fiction"]', '["Adventure"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:86', 'gutenberg', '86', 'A Connecticut Yankee in King Arthur''s Court', 'Mark Twain', 53000, '["Arthurian romances -- Adaptations"]', '["Satire"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:2852', 'gutenberg', '2852', 'The Hound of the Baskervilles', 'Arthur Conan Doyle', 52000, '["Detective and mystery stories"]', '["Detective Fiction"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:175', 'gutenberg', '175', 'The Phantom of the Opera', 'Gaston Leroux', 51000, '["Horror tales"]', '["Gothic"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:844', 'gutenberg', '844', 'The Importance of Being Earnest', 'Oscar Wilde', 50000, '["Comedy plays"]', '["Plays"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:74', 'gutenberg', '74', 'The Adventures of Tom Sawyer', 'Mark Twain', 49000, '["Adventure stories"]', '["Adventure"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:45', 'gutenberg', '45', 'Anne of Green Gables', 'L. M. Montgomery', 48000, '["Girls -- Fiction"]', '["Children"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:23', 'gutenberg', '23', 'Narrative of the Life of Frederick Douglass, an American Slave', 'Frederick Douglass', 47000, '["Enslaved persons -- United States -- Biography"]', '["Biography"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:829', 'gutenberg', '829', 'Gulliver''s Travels', 'Jonathan Swift', 46000, '["Satire"]', '["Adventure"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:69087', 'gutenberg', '69087', 'The Murder of Roger Ackroyd', 'Agatha Christie', 45000, '["Detective and mystery stories"]', '["Detective Fiction"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:3268', 'gutenberg', '3268', 'The Mysteries of Udolpho', 'Ann Radcliffe', 44000, '["Gothic fiction"]', '["Gothic"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:67098', 'gutenberg', '67098', 'Winnie-the-Pooh', 'A. A. Milne', 43000, '["Animals -- Juvenile fiction"]', '["Children"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:12', 'gutenberg', '12', 'Through the Looking-Glass', 'Lewis Carroll', 42000, '["Fantasy fiction"]', '["Children"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:203', 'gutenberg', '203', 'Uncle Tom''s Cabin', 'Harriet Beecher Stowe', 41000, '["Enslaved persons -- Fiction"]', '["Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:583', 'gutenberg', '583', 'The Woman in White', 'Wilkie Collins', 40000, '["Gothic fiction"]', '["Detective Fiction"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:696', 'gutenberg', '696', 'The Castle of Otranto', 'Horace Walpole', 39000, '["Gothic fiction"]', '["Gothic"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:289', 'gutenberg', '289', 'The Wind in the Willows', 'Kenneth Grahame', 38000, '["Animals -- Fiction"]', '["Children"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:4276', 'gutenberg', '4276', 'North and South', 'Elizabeth Gaskell', 37000, '["Bildungsromans"]', '["Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:22120', 'gutenberg', '22120', 'The Canterbury Tales', 'Geoffrey Chaucer', 36000, '["Christian pilgrims and pilgrimages -- Poetry"]', '["Poetry"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:1513', 'gutenberg', '1513', 'Romeo and Juliet', 'William Shakespeare', 36000, '["Vendetta -- Drama","Conflict of generations -- Drama"]', '["Plays","Tragedy"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:932', 'gutenberg', '932', 'The Fall of the House of Usher', 'Edgar Allan Poe', 35000, '["Horror tales"]', '["Horror"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:64317', 'gutenberg', '64317', 'The Great Gatsby', 'F. Scott Fitzgerald', 35000, '["Long Island (N.Y.) -- Fiction"]', '["Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:6124', 'gutenberg', '6124', 'Pamela, or Virtue Rewarded', 'Samuel Richardson', 34000, '["Epistolary fiction"]', '["Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:2641', 'gutenberg', '2641', 'A Room with a View', 'E. M. Forster', 33000, '["British -- Italy -- Fiction"]', '["Romance","Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:77', 'gutenberg', '77', 'The House of the Seven Gables', 'Nathaniel Hawthorne', 33000, '["Haunted houses -- Fiction"]', '["Gothic"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:16328', 'gutenberg', '16328', 'Beowulf', 'Anonymous', 32000, '["Epic poetry, English (Old)"]', '["Poetry","Mythology"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:610', 'gutenberg', '610', 'Idylls of the King', 'Alfred Tennyson', 32000, '["Arthur, King -- Poetry"]', '["Poetry"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:6053', 'gutenberg', '6053', 'Evelina', 'Fanny Burney', 31000, '["Bildungsromans"]', '["Classics"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:2787', 'gutenberg', '2787', 'An Old-Fashioned Girl', 'Louisa May Alcott', 30000, '["Friendship -- Juvenile fiction"]', '["Children"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:2265', 'gutenberg', '2265', 'Hamlet', 'William Shakespeare', 29000, '["Denmark -- Drama"]', '["Plays"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:56621', 'gutenberg', '56621', 'Aurora Leigh', 'Elizabeth Barrett Browning', 28000, '["Novels in verse"]', '["Poetry"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:70841', 'gutenberg', '70841', 'Robinson Crusoe', 'Daniel Defoe', 27000, '["Adventure stories"]', '["Adventure"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:66084', 'gutenberg', '66084', 'Sir Gawain and the Green Knight', 'Anonymous', 26000, '["Arthurian romances"]', '["Mythology"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:64636', 'gutenberg', '64636', 'Rip Van Winkle', 'Washington Irving', 25000, '["Fantasy fiction"]', '["Short Stories"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:67979', 'gutenberg', '67979', 'The Blue Castle', 'L. M. Montgomery', 24500, '["Young women -- Fiction"]', '["Romance"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:778', 'gutenberg', '778', 'Five Children and It', 'E. Nesbit', 24000, '["Wishes -- Fiction"]', '["Children"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:1063', 'gutenberg', '1063', 'The Cask of Amontillado', 'Edgar Allan Poe', 23000, '["Horror tales, American","Revenge -- Fiction"]', '["Short Stories","Horror"]', '[]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:3189', 'gutenberg', '3189', 'Sketches New and Old', 'Mark Twain', 22000, '["Humorous stories, American"]', '["Short Stories"]', '["The Celebrated Jumping Frog of Calaveras County"]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:512', 'gutenberg', '512', 'Mosses from an Old Manse', 'Nathaniel Hawthorne', 21000, '["Short stories, American"]', '["Short Stories","Gothic"]', '["Rappaccini''s Daughter"]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:10623', 'gutenberg', '10623', 'Plays', 'Susan Glaspell', 20000, '["American drama"]', '["Plays","One Act Plays"]', '["Trifles"]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:1041', 'gutenberg', '1041', 'Shakespeare''s Sonnets', 'William Shakespeare', 19000, '["English poetry","Sonnets, English"]', '["Poetry"]', '["Sonnet 18","Sonnet 73","Sonnet 116","Sonnet 130"]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:8601', 'gutenberg', '8601', 'The Early Poems of Alfred Lord Tennyson', 'Alfred Tennyson', 18000, '["English poetry -- 19th century"]', '["Poetry"]', '["Ulysses"]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:16376', 'gutenberg', '16376', 'Browning''s Shorter Poems', 'Robert Browning', 17000, '["English poetry"]', '["Poetry"]', '["My Last Duchess"]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:12242', 'gutenberg', '12242', 'Poems by Emily Dickinson, Three Series, Complete', 'Emily Dickinson', 16000, '["American poetry"]', '["Poetry"]', '["Because I could not stop for Death","I''m Nobody! Who are you?"]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('gutenberg:1459', 'gutenberg', '1459', 'Prufrock and Other Observations', 'T. S. Eliot', 15000, '["Poetry"]', '["Poetry"]', '["The Love Song of J. Alfred Prufrock"]', 'active', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
